[package]
name = "ley"
version = "0.1.0"
edition = "2021"
description = "A simple game launcher"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
sysinfo = "0.30"
toml = "0.8"

[profile.release]
panic = "abort"
strip = true
